### PR TITLE
[WIP] baseline frontend work

### PR DESCRIPTION
**Pull request by barbados-clemens**
get the basics of the frontend working with the MVP backend

- [x] Working Login/Logout
- [ ] CRUD Kitchen
- [ ] CRUD for items
- [ ] CRUD Memberships

### CODE REVIEW

**Comment by barbados-clemens** [comment]
@karnthis Working on integrating with the backend for signup/login. 

Just a couple questions.
1. Can you make the endpoint return JSON instead of plain text for a response. 
i.e. {"error": "passwords don't match"}
2. when there's an error should there be a 201 status code? I feel like it should be a 400, since 201 means created, but we shouldn't be creating a user if the signup details were invalid. We should throw a 4xx code since it was bad data from the client. 
3. Is there a reason why `/api/user/id` isn't returning the user object?
    - Steps to reproduce
        1. Signup with new user
        1. Login with new user
        1. Use token from logging in and hit endpoint `/api/user/userId` I get back blank.

**Comment by karnthis** [comment]
Is this ready to commit now that we sorted out the issue with adding items?

**Comment by barbados-clemens** [comment]
Give me this weekend, I'll get it to a mergable state.

**Comment by karnthis** [comment]
Baseline works for now, merging for new starting point

**Pull request merged**
